apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  ENV: {{ .Values.configMap.env }}
  PG_HOSTNAME: {{ .Values.configMap.pgHostname }}
  PG_PORT: !!str {{ .Values.configMap.pgPort }}

  PG_USER: {{ .Values.configMap.pgUser }}
  PG_PASSWORD: !!str {{ .Values.configMap.pgPassword }}

  INGESTION_BUCKET_URL: !!str {{ .Values.configMap.ingestionBucketUrl }}

  REQUEST_LOGGING_LEVEL: {{ .Values.configMap.requestLoggingLevel }}
  LOGGING_FORMAT: !!str {{ .Values.configMap.loggingFormat }}
