apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
   - port: {{ .Values.service.port }}
     targetPort: {{ .Values.service.targetPort }}
  selector:
   app: {{ .Values.service.selector }}